Erlaube Satzungsänderungen auf Vorschlag von Aufsichtsbehörden
chaos-jetzt/verein pull request #16
Opened 2024-05-20 09:28 UTC by septem9er

Hiermit wird dem Vorstand gestattet Satzungsänderungen eigenständig zu beschließend, die von Aufischtsbehörden vorgeschlagen wurden. So kann die Satzung geändert werden ohne das eine neue MV einberufen werden muss, wenn, insbesondere nach der Vereinsgründung oder bei Satzungsänderungen, Aufsichtsbehörden die Satzung bemängeln und die Eintragung verweigern.

2024-05-21 14:50 UTC, n0th1ng-m4tt3r5 approved these changes
Klingt sinnvoll.

2024-05-24 23:59 UTC, teismar submitted a review, later dismissed
Klingt sehr gut so können wir schnell auf gesetzliche "Forderungen" reagieren 👍🏼

2024-05-25 00:02 UTC, e1mo requested changes

2024-05-25 00:02 UTC, e1mo commented on satzung.md
> -    3. die Entlastung des Vorstandes und der Kassenprüfenden,
Diese Änderung erschließt sich mir nicht. Was ist die Motivation dahinter?

2024-05-25 00:09 UTC, Proliecan requested changes

2024-05-25 00:09 UTC, Proliecan commented on satzung.md
> -    3. die Entlastung des Vorstandes und der Kassenprüfenden,
Warum?

2024-05-25 00:09 UTC, Proliecan commented on satzung.md
> +7. Der Vorstand kann Satzungsänderungen, die von Aufsichts-, Gerichts- oder Finanzbehörden, insbesondere dem Vereinsregister angeregt werden, mit einfacher Mehrheit der abgegebenen Stimmen in einer V
Das ist zu allgemein.
Zumindest sollten die Aufsichtsbehörden spezifiziert werden.

Außerdem wird diese Klausel ausdrücklich von BGB§33 (Satzungsänderung) verboten, so wie ich das lese.

2024-05-25 07:12 UTC, septem9er commented on satzung.md
> -    3. die Entlastung des Vorstandes und der Kassenprüfenden,
Das war ausversehen, ich hatte daran rumgespielt und die Änderung nicht rückgängig gemacht.

2024-05-25 07:24 UTC, septem9er commented on satzung.md
> +7. Der Vorstand kann Satzungsänderungen, die von Aufsichts-, Gerichts- oder Finanzbehörden, insbesondere dem Vereinsregister angeregt werden, mit einfacher Mehrheit der abgegebenen Stimmen in einer V
Eine Regelung dieser Art ist nicht unüblich. Der Art, 33 BGB ist Teil der gesetzlichen Regelvereinsfassung, im Rahmen der Vereinsautonomie kann ein Verein jedoch eigene Reglungen wählen. So wie es ja bereits jetzt für die dort spezifizierten Mehrheiten zur Beschlussfassung geschehen ist.

2024-07-06 09:41 UTC, Proliecan requested changes

2024-07-06 09:41 UTC, Proliecan commented on satzung.md
> +7. Der Vorstand kann Satzungsänderungen, die von Aufsichts-, Gerichts- oder Finanzbehörden, insbesondere dem Vereinsregister angeregt werden, mit einfacher Mehrheit der abgegebenen Stimmen in einer V
Ich bin der Ansicht, dass der Verein über Satzungsänderungen gemeinsam diskutieren und abstimmen sollte.

2024-09-07 13:47 UTC, septem9er commented
Bei jetzt6 wurde beschlossen dies nicht aufzunehmen.

2024-09-07 13:47 UTC, closed without merging