del: Vorstand kann wählen
chaos-jetzt/verein pull request #23
Opened 2024-05-25 11:05 UTC by teismar

Das dürfte uns rechtlich durch den Fleischwolf drehen.

2024-05-25 11:23 UTC, e1mo requested changes

2024-05-25 11:23 UTC, e1mo commented on satzung.md
> +5. Scheidet ein Vorstandsmitglied während seiner Amtszeit aus, agiert der verbleibende Vorstand übergangsweise bis zur nächsten Mitgliederversammlung. Sind zwei oder mehr der durch die Mitgliedervers
```suggestion
5. Sind zwei oder mehr der durch die Mitgliederversammlung gewählten Vorstandsmitglieder dauerhaft an der Ausübung ihres Amtes gehindert, so sind unverzüglich Nachwahlen anzuberaumen.
6. Die Abwahl eines Vorstandsmitglieds ist nur möglich, sofern zeitgleich eine Neubesetzung des freigewordenen Amtes gemäß dieser Satzung erfolgt.
```

2024-07-06 09:07 UTC, Proliecan requested changes
Es muss stehts eine ungerade Anzahl von mindestens drei Vorstandsmitgliedern garantiert sein, damit der Vorstand als Vereinsorgan beschlussfähig bleibt.
Es darf innerhalb des Vorstandes keine Stimmgleichheit für und gegen eine Sache entstehen können.

2024-09-07 14:27 UTC, Proliecan approved these changes

2024-12-14 12:20 UTC, makuru-dd approved these changes

2024-12-14 12:20 UTC, Proliecan approved these changes
is ok.

2024-12-14 12:20 UTC, ledge8 approved these changes
basst

2024-12-14 12:21 UTC, merged